### ISSUE TITLE
POC: interfacing with existing data sources

### ISSUE THREAD

**Issue by jamalv** [teamforus/research-and-development#40]
# poc-connecting-data-sources
## Background / Context
**Goal/user story:** Often validators will have existing databases, how will we connect with these?

**More:** Look into the concept of oracles?

## Hypothesis:
Offer the validator an API. We can offer SDKs to simplify the process of connecting to the API.
## Method
*documentation/code*

## Result
*present findings*

## Recommendation
*write recomendation*

**Comment by maxvisser** [comment]
A validator like 'Kadaster', 'RDW' or an other government entity needs to comply to the new GDPR legislation. When a citizen of the EU request insight in their own information, an organisation needs to comply.

Steps:
- Citizen files a 'insight' request to Kadaster.
- Kadaster makes a JSON object, thats formatted so that it can be used by the Forus Platform
- Kadaster signs this JSON object using their private key.
- Kadaster responds with a signed JSON object. 
- The citizen will encrypt this object using their own private key.
- The citizen will upload this information to IPFS
- The citizen registers the claim from Kadaster on the Ethereum blockchain by submitting the IPFS hash (location), issuer (Kadasters public key)

This issue should be about how we want Kadaster to format their data and where a citizen can go to retrieve the JSON object.

**Comment by maxvisser** [comment]
https://github.com/teamforus/research-and-development/tree/RES002-interfacing-with-existing-data-sources/res002-interfacing-with-existing-data-sources

**Comment by jamalv** [comment]
merged to develop in: https://github.com/teamforus/research-and-development/pull/71
